name: panvimdoc
on:
  push:
    branches:
      - '**'
    paths: 
      - README.md
      - .github/workflows/panvimdoc.yml
      - doc/**
  workflow_dispatch:
jobs:
  docs:
    runs-on: ubuntu-latest
    name: pandoc to vimdoc
    steps:
      - uses: actions/checkout@v2

      - name: preformat README.md
        run: |
          mkdir tmp_preformat_readme
          cp README.md tmp_preformat_readme/README.md
          sed -E -e 's/\[!(NOTE|WARNING|IMPORTANT)\]/`\1`/Ig' -e 's/<summary>(.+)<\/summary>/- \1\r/g' \
            -e 's/<a.*href.*"(.+)".*>(.+)<\/a>/[\2](\1)/g' < README.md > tmp_preformat_readme/README.md

      - name: panvimdoc
        uses: kdheepak/panvimdoc@main
        with:
          vimdoc: kitty-scrollback.nvim
          pandoc: "tmp_preformat_readme/README.md"
          version: "NVIM v0.10+"
          toc: true
          demojify: true
          dedupsubheadings: false
          treesitter: true

      - name: cleanup preformat README.md
        run: |
          rm -rf tmp_preformat_readme

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: ${{ github.head_ref }}
          commit_message: "chore(build): auto-generate vimdoc"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"

